services:
  db:
    image: mariadb:11.3
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpwd
      MYSQL_DATABASE: moodle
      MYSQL_USER: moodle
      MYSQL_PASSWORD: moodlepwd
    volumes:
      - db_data:/var/lib/mysql

  moodle:
    image: brandkern/moodle:4.5-latest
    restart: always
    ports:
      - "8080:80"
    environment:
      DB_HOST: db
      DB_NAME: moodle
      DB_USER: moodle
      DB_PASS: moodlepwd
      WWWROOT: http://localhost:8080
    volumes:
      - moodle_data:/var/www/moodledata
    depends_on:
      - db

volumes:
  db_data:
  moodle_data: